- name: Enable to install nginx.
  shell: "amazon-linux-extras enable nginx1.12"
  become: yes

- name: Install nginx
  become: yes
  yum:
    name: nginx
  tags:
    - nginx

- name: Put nginx.conf
  become: yes
  template:
    src: roles/nginx/templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  tags:
    - nginx

- name: Put local.conf
  become: yes
  template:
    src: roles/nginx/templates/local.conf.j2
    dest: /etc/nginx/conf.d/local.conf

- name: Set auto start nginx
  become: yes
  shell: chkconfig nginx on
  tags:
    - nginx

- name: Restart nginx
  become: yes
  shell: systemctl start nginx
  tags:
    - nginx

- name: Change permissions fo nginx
  become: yes
  file:
    path=/{{ item }}
    state=directory
    mode=0755
    recurse=yes
  with_items:
    - tmp
    - var
  tags:
    - nginx